### ISSUE TITLE
[FEATURE REQUEST] Add support for custom drush default parameters 

### ISSUE THREAD

**Issue by mickaelperrin** [guncha25/drupal-codeception#2]
Hi,

I just started to play around with codeception and Drupal 8. Thanks a lot for your project it looks like very helpful.

I am working on a multi-domain Drupal 8 website and need to provide the drush `uri`parameter to grab adequate settings.

I was wondering what would be the best way to implement it, here is what I was thinking about:
- add a 4th parameter in Drush::runDrush ($defaultParameters)
- grab the default settings array from config, like working_directory in DrupalDrush::runDrush

Is it ok for you, or would you prefer to : 
- add a simple uri parameter instead of defaultParameters
- remove also the working_directory parameter so we could use the `path` parameter. We would have to check if working_directory to populate the defaultParameters to prevent break of existing installations.

Thanks for your lights.

**Comment by guncha25** [comment]
@mickaelperrin Thank you for your suggestions. I went for a solution that could help without breaking compatibility. Now DrupalDrush::runDrush accepts options array where you can provide uri like so 
`$I->runDrush('uli', ['uri' => 'http://mydomain.com']);`
Alternatively you can provide default options for Drupal drush in config.

No changes made in Drush utility as if you are using plain Util then you can manage default argument injection. In order to swap uri or root and manipulate any of drush options i would recommend using codeception-config-module to retrieve data at runtime and inject it in to DrupalDrush::runDrush.

Hope this helps. If not feel free to reopen this issue.
